
import java.awt.Point;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javafx.util.Pair;
import javax.swing.JButton;
import javax.swing.Timer;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author tuans
 */
public class Screen extends javax.swing.JFrame{

    /**
     * Creates new form Screen
     */
    int[][] matrix;
    int moveCount=0,time=0;
    Timer clock;
    public Screen() {
        initComponents();
        initMatrix();
        initTimer();
    }
    void initTimer(){
        clock=new Timer(1000, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                time++;
                lbTime.setText(time+"");
            }
        });
        synchronized(clock){      
            clock.start();
        }
        
    }
    void initMatrix(){
        String choose=(String) cbChoose.getSelectedItem();
        if (choose.compareTo("3x3")==0){
            matrix=new int[][]{{1,2,3},{4,5,6},{7,8,0}};
        }else{
            matrix=new int[4][4];
        }
    }
    Pair findNumberInMaxtrix(int number){
        int xPos=0,yPos=0;
        Boolean foundPosition=false;
        for (xPos=0;xPos<matrix.length;xPos++){
            for (yPos=0;yPos<matrix[xPos].length;yPos++){
                if (matrix[xPos][yPos]==number){
                    return new Pair(xPos, yPos);
                }
            }
        }
        return null;
    }
    int nextToNum(int number1,int number2){
        Pair pos1=findNumberInMaxtrix(number1);
        Pair pos2=findNumberInMaxtrix(number2);
        int x1=(int) pos1.getKey(),y1=(int) pos1.getValue(),x2=(int) pos2.getKey(),y2=(int) pos2.getValue();
        if (x1-x2==1 && y1==y2) return 1;
        if (y1-y2==1 && x1==x2) return 2;
        if (y2-y1==1 && x1==x2) return 3;
        if (x2-x1==1 && y1==y2) return 4;
        return 0;
    }
    JButton convertNumToButton(int number){
        if (number==1) return bt1;
        if (number==2) return bt2;
        if (number==3) return bt3;
        if (number==4) return bt4;
        if (number==5) return bt5;
        if (number==6) return bt6;
        if (number==7) return bt7;
        if (number==8) return bt8;
        return bt0;
    }
    Boolean checkState(){
        int size=matrix.length;
        int numberCheck=0;
        for (int i=0;i<size;i++){
            for (int j=0;j<size;j++){
                numberCheck++;
                if (numberCheck<=9)
                if (matrix[i][j]!=numberCheck) return false;
            }
        }
        return true;
    }
    void changePositionNumber(int number){
        
        if (nextToNum(number,0)!=0){
            Pair pos1=findNumberInMaxtrix(number);
            Pair pos2=findNumberInMaxtrix(0);
            int x1=(int) pos1.getKey(),y1=(int) pos1.getValue(),
                    x2=(int) pos2.getKey(),y2=(int) pos2.getValue();
            JButton bt=convertNumToButton(number);
            Point p1 = bt.getLocation();
            Point p2 = bt0.getLocation();
            bt.setLocation(p2);
            bt0.setLocation(p1);
            int temp=matrix[x1][y1];
            matrix[x1][y1]=matrix[x2][y2];
            matrix[x2][y2]=temp;
            
//            moveCount++;
//            lbCountMove.setText(moveCount+"");
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        lb3x3 = new javax.swing.JPanel();
        bt1 = new javax.swing.JButton();
        bt2 = new javax.swing.JButton();
        bt3 = new javax.swing.JButton();
        bt4 = new javax.swing.JButton();
        bt5 = new javax.swing.JButton();
        bt6 = new javax.swing.JButton();
        bt7 = new javax.swing.JButton();
        bt8 = new javax.swing.JButton();
        bt0 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnNewGame = new javax.swing.JButton();
        cbChoose = new javax.swing.JComboBox<>();
        lbCountMove = new javax.swing.JTextField();
        lbTime = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lb3x3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lb3x3.setLayout(new java.awt.GridBagLayout());

        bt1.setText("1");
        bt1.setMaximumSize(new java.awt.Dimension(50, 50));
        bt1.setMinimumSize(new java.awt.Dimension(50, 50));
        bt1.setPreferredSize(new java.awt.Dimension(50, 50));
        bt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        lb3x3.add(bt1, gridBagConstraints);

        bt2.setText("2");
        bt2.setMaximumSize(new java.awt.Dimension(50, 50));
        bt2.setMinimumSize(new java.awt.Dimension(50, 50));
        bt2.setPreferredSize(new java.awt.Dimension(50, 50));
        bt2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt2ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        lb3x3.add(bt2, gridBagConstraints);

        bt3.setText("3");
        bt3.setMaximumSize(new java.awt.Dimension(50, 50));
        bt3.setMinimumSize(new java.awt.Dimension(50, 50));
        bt3.setPreferredSize(new java.awt.Dimension(50, 50));
        bt3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt3ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        lb3x3.add(bt3, gridBagConstraints);

        bt4.setText("4");
        bt4.setMaximumSize(new java.awt.Dimension(50, 50));
        bt4.setMinimumSize(new java.awt.Dimension(50, 50));
        bt4.setPreferredSize(new java.awt.Dimension(50, 50));
        bt4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt4ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        lb3x3.add(bt4, gridBagConstraints);

        bt5.setText("5");
        bt5.setMaximumSize(new java.awt.Dimension(50, 50));
        bt5.setMinimumSize(new java.awt.Dimension(50, 50));
        bt5.setPreferredSize(new java.awt.Dimension(50, 50));
        bt5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt5ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        lb3x3.add(bt5, gridBagConstraints);

        bt6.setText("6");
        bt6.setMaximumSize(new java.awt.Dimension(50, 50));
        bt6.setMinimumSize(new java.awt.Dimension(50, 50));
        bt6.setPreferredSize(new java.awt.Dimension(50, 50));
        bt6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt6ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        lb3x3.add(bt6, gridBagConstraints);

        bt7.setText("7");
        bt7.setMaximumSize(new java.awt.Dimension(50, 50));
        bt7.setMinimumSize(new java.awt.Dimension(50, 50));
        bt7.setPreferredSize(new java.awt.Dimension(50, 50));
        bt7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt7ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        lb3x3.add(bt7, gridBagConstraints);

        bt8.setText("8");
        bt8.setMaximumSize(new java.awt.Dimension(50, 50));
        bt8.setMinimumSize(new java.awt.Dimension(50, 50));
        bt8.setPreferredSize(new java.awt.Dimension(50, 50));
        bt8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt8ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        lb3x3.add(bt8, gridBagConstraints);

        bt0.setMaximumSize(new java.awt.Dimension(50, 50));
        bt0.setMinimumSize(new java.awt.Dimension(50, 50));
        bt0.setPreferredSize(new java.awt.Dimension(50, 50));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        lb3x3.add(bt0, gridBagConstraints);

        jLabel1.setText("Move counts: ");

        jLabel2.setText("Elapsed: ");

        jLabel3.setText("Size:");

        btnNewGame.setText("New game");
        btnNewGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewGameActionPerformed(evt);
            }
        });

        cbChoose.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "3x3", "4x4" }));

        lbCountMove.setEditable(false);
        lbCountMove.setBackground(new java.awt.Color(204, 204, 204));
        lbCountMove.setText("0");
        lbCountMove.setBorder(null);

        lbTime.setEditable(false);
        lbTime.setBackground(new java.awt.Color(204, 204, 204));
        lbTime.setText("0");
        lbTime.setBorder(null);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(lb3x3, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(169, 169, 169)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnNewGame)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lbCountMove))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(39, 39, 39)
                                .addComponent(lbTime, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cbChoose, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(136, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(lb3x3, javax.swing.GroupLayout.DEFAULT_SIZE, 219, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1)
                    .addComponent(lbCountMove, javax.swing.GroupLayout.DEFAULT_SIZE, 21, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbTime, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cbChoose, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addComponent(btnNewGame)
                .addGap(47, 47, 47))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt1ActionPerformed
        // TODO add your handling code here:
        changePositionNumber(1);
    }//GEN-LAST:event_bt1ActionPerformed

    private void bt2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt2ActionPerformed
        // TODO add your handling code here:
        changePositionNumber(2);
    }//GEN-LAST:event_bt2ActionPerformed

    private void bt3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt3ActionPerformed
        // TODO add your handling code here:
        changePositionNumber(3);
    }//GEN-LAST:event_bt3ActionPerformed

    private void bt4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt4ActionPerformed
        // TODO add your handling code here:
        changePositionNumber(4);
    }//GEN-LAST:event_bt4ActionPerformed

    private void bt5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt5ActionPerformed
        // TODO add your handling code here:
        changePositionNumber(5);
    }//GEN-LAST:event_bt5ActionPerformed

    private void bt6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt6ActionPerformed
        // TODO add your handling code here:
        changePositionNumber(6);
    }//GEN-LAST:event_bt6ActionPerformed

    private void bt7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt7ActionPerformed
        // TODO add your handling code here:
        changePositionNumber(7);
    }//GEN-LAST:event_bt7ActionPerformed

    private void bt8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt8ActionPerformed
        // TODO add your handling code here:
        changePositionNumber(8);
    }//GEN-LAST:event_bt8ActionPerformed

    private void btnNewGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewGameActionPerformed
        // TODO add your handling code here:
        initMatrix();
        moveCount=0;
        time=0;
        clock.stop();
    }//GEN-LAST:event_btnNewGameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Screen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt0;
    private javax.swing.JButton bt1;
    private javax.swing.JButton bt2;
    private javax.swing.JButton bt3;
    private javax.swing.JButton bt4;
    private javax.swing.JButton bt5;
    private javax.swing.JButton bt6;
    private javax.swing.JButton bt7;
    private javax.swing.JButton bt8;
    private javax.swing.JButton btnNewGame;
    private javax.swing.JComboBox<String> cbChoose;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel lb3x3;
    private javax.swing.JTextField lbCountMove;
    private javax.swing.JTextField lbTime;
    // End of variables declaration//GEN-END:variables

}
